---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo1-db-secret
  namespace: demo1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm-store
    kind: SecretStore
  target:
    name: demo1-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        PGDATABASE: "{{ .PGDATABASE }}"
        PGUSERNAME: "{{ .PGUSERNAME }}"
        PGPASSWORD: "{{ .PGPASSWORD }}"
        PGENDPOINT: "{{ .PGENDPOINT }}"
  dataFrom:
    - extract:
        key: db_credentials
...
